# 注意yaml语法格式，冒号后面应该有一个空格
# 禁用命令列表
# 例子:- 'man*'  屏蔽所有以man开头任意有效字符结尾的命令,'*'表示0个或者多个有效字符
# 例子:- '*addp' 屏蔽所有以任意有效字符开头addp结尾的命令
# 例子:- 'man?addp' 屏蔽以man开头,addp结尾,中间为任意一个有效字符的命令
# 什么是有效字符:大小写英文字母,数字,下划线_,短横线-
# 例子:- '+list' 白名单模式,允许list命令.注意:白名单的命令一定要写在上面!!!因为整个匹配过程是从上往下的,匹配成功就直接返回了
# 白名单模式不能使用通配符(*?),也就是说'+'不能和'?''*'一起使用,因为没有使用正则表达式,只是比较两个字符串是否相等(忽略大小写)
list:
  - 'op'
  - 'deop'
  - 'stop'
  - 'reload'

# 白名单玩家列表，在白名单内的玩家执行命令将不受限制
playerWhiteList:
  - 'test'

# 检测配置文件更改的频率(时间单位:sec),默认每3秒检测一次,最小1秒,最大60秒
configUpdateInterval: 3

# 拦截玩家执行的命令时给玩家发出的提示信息，提示信息写在双引号内
denyMessage: ""
