name: CommandBlock
main: me.commandBlock.CommandBlock
version: 1.4.0
authors: [slinar]
description: []
commands:
  cb:
    description: "测试指令" #指令的注解
    usage: §c/cb <reload> - 重载配置文件
           §c/cb <debug> <on/off> - 调试信息开关